CREATE DATABASE COISAS;

USE COISAS;

CREATE TABLE CATEGORIA(
    ID_CAT INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE CALIBRE(
    ID_CAL INT AUTO_INCREMENT PRIMARY KEY,
    CAL_NOME VARCHAR(50),
    PRECO INT NOT NULL,
    ID_CAT INT NOT NULL,
    FOREIGN KEY (ID_CAT) REFERENCES CATEGORIA(ID_CAT)
);

CREATE TABLE USUARIO(
    CPF VARCHAR(14) PRIMARY KEY,
    EMAIL VARCHAR(60) NOT NULL UNIQUE,
    SENHA VARCHAR(40)NOT NULL,
    ADM TINYINT DEFAULT 0
);

CREATE TABLE TELEFONE(
    CPF VARCHAR(14),
    TEL INT NOT NULL,
    PRIMARY KEY(CPF, TEL),
    FOREIGN KEY (CPF) REFERENCES USUARIO(CPF)
);

CREATE TABLE ENDERECO(
    CPF VARCHAR(14) NOT NULL PRIMARY KEY,
    CEP VARCHAR(9) NOT NULL,
    RUA VARCHAR(50) NOT NULL,
    NUMERO INT NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    FOREIGN KEY (CPF) REFERENCES USUARIO(CPF)
);

INSERT INTO CATEGORIA VALUES
(NULL, "Explosivo"),
(NULL, "FMJ"),
(NULL, "Hollow point"),
(NULL, "Incendiário");

INSERT INTO CALIBRE VALUES(NULL, "20mm", 6, 2), (NULL, ".50", 70, 4);

INSERT INTO USUARIO VALUES("484944894", "adm@adm.com", "d033e22ae348aeb5660fc2140aec35850c4da997", 1);

ALTER TABLE CALIBRE
ADD LANCAMENTO BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE CALIBRE
ADD ADD_DATA DATE NOT NULL DEFAULT (CURRENT_DATE());